<?php
// Change this for the title - all titles start with "No2ID -" 
$page_title = "Labour's poll tax";
// add ../ before inc if page is within a directory - only need to do this on top include
require_once('../inc/pageHead.php');?>
<!-- Put your page in here -->
<h1>Labour's poll tax</h1>
<p>In the wake of this week&rsquo;s report on electoral fraud in Birmingham, David Blunkett, the ex-Home Secretary, has suggested that the way to deal with election fraud is to enforce voter registration backed up by a compulsory identity card.</p>
<p>Not content to stay on the sidelines having resigned his post some three or more months ago, Blunkett is still harping on about the wonders of ID cards but this time on a subject that is not included in the Bill, and has not been mentioned before &ndash; another case of ID cards being a solution grasping around desperately for a problem, and failing. </p>
<p>Speaking on <a href="http://news.bbc.co.uk/1/hi/uk_politics/vote_2005/frontpage/4418753.stm">Question Time</a>, neither Blunkett nor <a href="https://www.no2id.net/news/newsblog/index.php?p=114">a moments sane reflection</a> gives any indication how ID cards would assist making postal voting more secure. Even if registering for a postal ballot required visiting some council office and proffering finger or eye to a bureaucrat&rsquo;s inspection, this process would not would stop someone else from using the postal vote thus gained on your behalf, as the ID card, finger and eye are not present for verification.</p>
<p>Perhaps Blunkett wishes to enforce an ID card check at the voting station, with a scanner in each one across the country - in addition to every hospital, surgery, local and central government office, every employer, point of sale, airport and seaport. With multiple voting stations in every constituency, the cost of this would represent a staggering waste of money, grossly inflating the scheme&rsquo;s costs beyond the current estimates of &pound;5.5bn.</p>
<p>Naturally, such a scheme would force people to have an identity card; have their identity, personal details, financial, medical and travel habits owned by the Home Secretary and accessible by faceless public servants, or see their right to vote removed &ndash; a feat of disenfranchisement that even the leaders of banana republics, the description used by Richard Mawrey QC in his report to depict the scale of the fraud in Birmingham last year, would be impressed by.</p>
<p> This is not the first time we have seen this attempted: fifteen years ago, the poll tax was introduced, tied to the electoral roll. Hundreds of thousands, perhaps as many as half a million people, &quot;<a href="http://www.charter88.com/pubs/violations/hodgson.html%20">committed electoral suicide</a>&quot; by deliberately not registering to vote in order to avoid the regressive tax that they were unwilling or, in many cases, simply unable to pay. </p>
<p><strong>ID cards will be Labour&rsquo;s Poll Tax</strong> -  they are controversial, they are objectionable on commonsense, practical and principled grounds, and they will force malcontents off the voting register or into the waiting arms of the National Identity Register. A case of win-win for government.</p>
<?php require_once('../inc/pageFooter.php');?>
